name: Auto Merge
on:
  pull_request_target:
    types: [labeled]

jobs:
  merge_when_ready:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - uses: actions/checkout@v5
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}